# Generated by Django 3.0.8 on 2020-09-21 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lectures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentname', models.CharField(max_length=100)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('p_video', models.FileField(blank=True, upload_to=lectures.models.p_video_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='StudentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_video', models.FileField(blank=True, null=True, upload_to=lectures.models.s_upload_path)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_video', to='lectures.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('student_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lectures.StudentVideo')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(blank=True, null=True, upload_to=lectures.models.p_image_upload_path)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_image', to='lectures.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturename', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('professor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_id', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='student_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lectures.Lecture'),
        ),
    ]
