# Generated by Django 3.0.8 on 2020-07-17 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0002_auto_20200716_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
