# Generated by Django 3.0.8 on 2020-07-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20200717_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='p_video',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='s_video',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lecture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lectures.Lecture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lectures.Assignment'),
            preserve_default=False,
        ),
    ]
