# Generated by Django 3.0.8 on 2020-07-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20200717_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='p_video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='s_video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
