# Generated by Django 3.0.8 on 2020-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20200717_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='p_video',
            field=models.FileField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='s_video',
            field=models.FileField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
