# Generated by Django 3.0.8 on 2020-07-17 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0006_auto_20200717_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='professor_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
