# Generated by Django 3.0.8 on 2020-07-19 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0007_auto_20200717_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='p_video',
            new_name='professor_video',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='s_video',
        ),
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Student_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_video', models.FileField(blank=True, upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_video',
            field=models.ManyToManyField(blank=True, related_name='student_videos', to='lectures.Student_video'),
        ),
    ]
