# Generated by Django 3.0.8 on 2020-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_auto_20200719_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(blank=True),
        ),
    ]
