# Generated by Django 3.0.8 on 2020-08-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_lecture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='image',
        ),
    ]
